name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]  # Selecciona amd64 y arm64 para arquitectura nativa

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf build-essential

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build Binary with Nuitka
        run: |
          nuitka --standalone --onefile --include-data-dir=apps=apps --output-filename=atlanti main.py

      - name: Upload binary for ${{ matrix.architecture }}
        uses: actions/upload-artifact@v3
        with:
          name: atlanti-${{ matrix.architecture }}-${{ github.ref_name }}
          path: atlanti
