name: Release Build

on:
  push:
    tags:
      - 'v*'

env:
  OUTPUT_DIR: output  # Directorio donde se generarán los binarios
  RELEASE_NAME: atlanti  # Nombre del archivo binario final

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-22.04-arm  # Runner para ARM si está configurado
            arch: arm64

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf build-essential

      - name: Install Nuitka
        run: |
          pip install nuitka

      - name: Verify architecture
        run: uname -m  # Paso de verificación de arquitectura para confirmar

      - name: Build Binary with Nuitka for ${{ matrix.arch }}
        run: |
          nuitka --standalone --onefile --include-data-dir=apps=apps --output-filename=${{ env.RELEASE_NAME }} main.py

      - name: Upload binary for ${{ matrix.arch }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RELEASE_NAME }}-${{ matrix.arch }}-${{ github.ref_name }}
          path: ${{ env.RELEASE_NAME }}
