name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [amd64, arm64]

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential patchelf

      - name: Install Nuitka and requirements
        run: |
          pip install nuitka
          pip install -r requirements.txt

      - name: Compile the application with Nuitka for ${{ matrix.architecture }}
        run: |
          nuitka --standalone --onefile --include-data-dir=apps=apps --output-filename=atlanti main.py

      - name: Rename and upload binary
        run: |
          mv atlanti output/atlanti-${{ matrix.architecture }}
        uses: actions/upload-artifact@v2
        with:
          name: atlanti-${{ matrix.architecture }}-${{ github.ref_name }}
          path: output/
