name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
      OUTPUT_DIR: /app/output  # Directorio donde se almacenará el binario compilado
      RELEASE_NAME: atlanti  # Nombre del binario final

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Binary with Nuitka for ${{ matrix.arch }}
        run: |
          # Crear el directorio de salida
          mkdir -p ${{ env.OUTPUT_DIR }}
          # Construcción multiplataforma
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            -t atlanti-builder:${{ matrix.arch }} \
            --build-arg ARCH=${{ matrix.arch }} \
            --output type=local,dest=${{ env.OUTPUT_DIR }} \
            .

      - name: Verify the compiled binary
        run: |
          ls -lh ${{ env.OUTPUT_DIR }}/
          file ${{ env.OUTPUT_DIR }}/atlanti  # Confirma la arquitectura del binario generado

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.RELEASE_NAME }}-${{ matrix.arch }}-${{ github.ref_name }}
          path: ${{ env.OUTPUT_DIR }}/atlanti
